branches:
  only:
  - RoboticsManual
  
before_install:
- sudo add-apt-repository ppa:jonathonf/texlive-2015 -y
- sudo apt-get update 
- sudo apt-get install texlive texlive-latex-extra texlive-lang-czechslovak

script:
- latex --version
- aptitude search texlive
- cd RoboticsManual
- mkdir _build
- mkdir _html
- pdflatex -output-directory _build _dokumentace.tex
- cd
- make4ht /RoboticsManual/_dokumentace.tex -d /RoboticsManual/_html
- ls -la /RoboticsManual/_html

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file:
  - ../RoboticsManual/_build/_dokumentace.pdf
  skip_cleanup: true
  on:
    tags: true
    branch: RoboticsManual
