branches:
  only:
  - RoboticsManual
  
before_install:
# MikTeX
#- sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys D6BC243565B2087BC3F897C9277A7293F59E4889
#- echo "deb http://miktex.org/download/ubuntu xenial universe" | sudo tee /etc/apt/sources.list.d/miktex.list
#- sudo apt-get update
#- sudo apt-get install miktex

# TeX Live 2015
#- sudo add-apt-repository ppa:jonathonf/texlive-2015 -y
- sudo apt-get update 
- sudo apt-get install texlive texlive-latex-extra texlive-lang-czechslovak
- mkdir make4ht
- cd make4ht
- git clone https://github.com/michal-h21/make4ht
- ls -la
- make

script:
- make4ht -v
- latex --version
- aptitude search texlive
- cd RoboticsManual
- mkdir _build
- mkdir _html
- pdflatex -output-directory _build _dokumentace.tex
- cd
- make4ht /RoboticsManual/_dokumentace.tex -d /RoboticsManual/_html
- ls -la /RoboticsManual/_html

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file:
  - ../RoboticsManual/_build/_dokumentace.pdf
  skip_cleanup: true
  on:
    tags: true
    branch: RoboticsManual
